### ISSUE TITLE
class-method-newlines incorrect with TS@2.1

### ISSUE THREAD

**Issue by bookman25** [jwbay/tslint-misc-rules#10]
Properties on a class are triggering this rule, not just methods with TypeScript 2.1.4

**Comment by bookman25** [comment]
Also looks like sort-imports rule is throwing errors when trying to run now.

**Comment by bookman25** [comment]
Appears to be an issue when there are 2 versions of TS in the repo.

**Comment by jwbay** [comment]
Any way to tell which version of TS this module required? Did it have its own version or pull from something higher?

**Comment by bookman25** [comment]
It was because there were 2 versions of TS's referenced in the repo.  But only 1 version was actually necessary.  Just had to collapse the 2 references in the lock file to fix.
