### ISSUE TITLE
no-braces-for-single-line-arrow-functions auto-fix has lots of bugs

### ISSUE THREAD

**Issue by bookman25** [jwbay/tslint-misc-rules#14]
() => { statement; statement2; }
() => { return returnX; }
() => { return {}; }

**Comment by jwbay** [comment]
I think I'm going to make this not a rule violation - `() => { statement; statement2; }`.  Not only does that function body really need braces, which means it's outside the domain of this rule, but it ensures all violations of this rule can be autofixed. 

A separate rule with narrower scope may make sense for that. Arrow functions with multiple statements need one statement per line, or something.

**Comment by jwbay** [comment]
Actually one statement per line seems like it should be its own rule, outside of the scope of arrow functions
