### ISSUE TITLE
no-unnecessary-parens-for-arrow-function-arguments destructuring

### ISSUE THREAD

**Issue by bookman25** [jwbay/tslint-misc-rules#7]
The following fails to lint and the parentheses are required in this case.
```
Promise.all([some, promises])
  .then(([result, values]) => {});
```

**Comment by bookman25** [comment]
Never mind, this appears to be fixed.  Editor had to be restarted to pick up new rules.

**Comment by jwbay** [comment]
`function().then(({ x: y }) => (x + y))`
